model:
  name: "Unbabel/TowerInstruct-7B-v0.1"
  use_cache: false
  torch_dtype: "float16"
  device_map: "auto"

lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  bias: "none"

training:
  output_dir: "./checkpoints"
  num_train_epochs: 5
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 8
  learning_rate: 0.0002  # Cambiado de 2e-4 a formato decimal
  warmup_steps: 100
  logging_steps: 25
  save_steps: 250
  eval_steps: 250
  save_total_limit: 3
  fp16: false
  bf16: true
  gradient_checkpointing: true
  optim: "adamw_torch"
  max_grad_norm: 1.0
  
data:
  max_length: 256
  dataset_name: "facebook/flores"
  source_lang: "spa_Latn"
  target_lang: "glg_Latn"